services:
  - type: web
    name: ggongali-chongchongi-100days
    runtime: static
    branch: main
    rootDir: app
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    autoDeployTrigger: commit
